
describe('Main view tests', () => {
  
  it('Should be able to visit title, mission & game views and render correct elements', () => {
    cy.visit('http://localhost:3000')
      .get('h1')
      .contains('NUNSLINGER')
      .get('button')
      .contains('Confess Your Sins')
      .click()
      .url().should('include', '/missions')
      .get('button')
      .contains('Accept Mission')
      .click()
      .url().should('include', '/game')
      .get('audio')
      .should('have.prop', 'ended', false)
      .should('have.prop', 'duration', 121.913469)
      .get('.game-instructions')
      .get('button')
      .contains('Less reading, more shooting')
      .click()
      .should('have.length', 0)
      .get('progress')
      .should('have.value', 100)
      .get('.back-to-main-page')
      .click()
      .url().should('include', '/')
  })
});